parameters:
- name: fullRun
  displayName: Run full build and tests
  type: boolean
  default: false

trigger:
- master

pr:
- master

jobs:
# Configure, build, install, and test job
- job: 'linux_build'
  displayName: 'Linux Builds'
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 10
  variables:
    CTEST_OUTPUT_ON_FAILURE: 1
  strategy:
    matrix:
      gcc_latest:
        CXX_COMPILER: 'g++'
        CXX_FLAGS: "-O3 -fprofile-arcs -ftest-coverage"
        C_COMPILER: 'gcc'
        F_COMPILER: 'gfortran'
        BUILD_TYPE: 'release'
        APT_INSTALL: 'gfortran'

      clang_latest:
        CXX_COMPILER: 'clang++'
        CXX_FLAGS: "-O3 -std=c++14"
        C_COMPILER: 'clang'
        F_COMPILER: 'gfortran'
        BUILD_TYPE: 'release'
        APT_INSTALL: 'gfortran clang'

  steps:
  - checkout: self
    submodules: true
    displayName: "Checkout repos"
  - bash: |
      set -euo pipefail
      [[ -n "${APT_REPOSITORY:-}" ]] && echo "Add Repo ${APT_REPOSITORY}" && sudo add-apt-repository "${APT_REPOSITORY}"
      sudo apt-get update
      sudo apt-get install -y ${APT_INSTALL}
    displayName: "Apt-Get Packages"
  - bash: |
      set -euo pipefail
      command -v ${CXX_COMPILER}
      command -v ${C_COMPILER}
      command -v ${F_COMPILER}
      echo "Full run requested: ${{ parameters.fullRun }}"
      echo "Build reason: $(Build.Reason)"
      echo "" && echo "Ubuntu"
      lsb_release -a
      echo "" && echo "Uname:"
      uname -a
      echo "" && echo "Free:"
      free -m
      echo "" && echo "df:"
      df -h
      echo "" && echo "Ulimit:"
      ulimit -a
      echo "" && echo "Nprocs:"
      getconf _NPROCESSORS_ONLN
      echo "CXX Ver:"
      ${CXX_COMPILER} --version
      echo "F Ver:"
      ${F_COMPILER} --version
      echo "C Ver:"
      ${C_COMPILER} --version
    displayName: 'Build Environment'
  - bash: |
      set -euo pipefail
      cmake -S . -B build \
        -DCMAKE_C_COMPILER=${C_COMPILER} \
        -DCMAKE_CXX_COMPILER=${CXX_COMPILER} \
        -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
        -DCMAKE_INSTALL_PREFIX=$(Agent.BuildDirectory)/Install \
        -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" \
        -DLIBECPINT_MAX_UNROL=1 \
        -DLIBECPINT_MAX_L=4
    displayName: 'Configure Build'
  - bash: |
      set -euo pipefail
      cmake --build build --parallel
    displayName: 'Build'
    condition: and(succeeded(), or(ne(variables['Build.Reason'], 'PullRequest'), ${{ eq(parameters.fullRun, true) }}))
  - bash: |
      set -euo pipefail
      ctest --test-dir build --output-on-failure
    displayName: 'Tests'
    condition: and(succeeded(), or(ne(variables['Build.Reason'], 'PullRequest'), ${{ eq(parameters.fullRun, true) }}))
  - bash: bash <(curl -s https://codecov.io/bash)
    displayName: 'Upload to codecov.io'
    condition: and(succeeded(), or(ne(variables['Build.Reason'], 'PullRequest'), ${{ eq(parameters.fullRun, true) }}))
